# Generated by Django 2.2.7 on 2020-07-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('app_text1', models.TextField()),
                ('app_text2', models.TextField()),
                ('github', models.CharField(max_length=140)),
                ('school', models.CharField(max_length=200)),
                ('first_hackathon', models.CharField(max_length=5)),
                ('timezone', models.CharField(max_length=50)),
                ('is_CA', models.BooleanField(default=False)),
                ('graders', models.CharField(default='', max_length=140)),
                ('num_graders', models.DecimalField(decimal_places=0, default=0, max_digits=1)),
                ('comments', models.TextField(default='')),
                ('status', models.CharField(default='N/A', max_length=30)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('check_in', models.BooleanField(default=False)),
            ],
        ),
    ]
