# Generated by Django 2.2.7 on 2020-07-11 02:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('app_text1', models.TextField()),
                ('app_text2', models.TextField()),
                ('github', models.CharField(max_length=140)),
                ('school', models.CharField(max_length=200)),
                ('first_pennapps', models.BooleanField()),
                ('timezone', models.CharField(max_length=10)),
                ('num_graders', models.DecimalField(decimal_places=0, max_digits=1)),
                ('status', models.BooleanField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('check_in', models.BooleanField()),
                ('graders', models.ManyToManyField(related_name='graders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
