# Generated by Django 2.2.7 on 2020-07-11 02:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='App',
            new_name='Application',
        ),
    ]
