# Generated by Django 2.2.7 on 2020-07-11 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20200711_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_CA',
            field=models.BooleanField(default=False),
        ),
    ]
