# Generated by Django 2.2.7 on 2020-07-11 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_application_is_ca'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='comments',
            field=models.TextField(default=''),
        ),
    ]
