# Generated by Django 2.2.7 on 2020-07-11 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_application_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='graders',
        ),
        migrations.AddField(
            model_name='application',
            name='graders',
            field=models.CharField(default='', max_length=140),
        ),
    ]
