# Generated by Django 2.2.7 on 2020-07-11 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_auto_20200711_0440'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='first_hackathon',
            field=models.BooleanField(default=True),
        ),
    ]
