# Generated by Django 2.2.7 on 2020-07-11 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_application_first_hackathon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='first_pennapps',
        ),
    ]
