# Generated by Django 2.2.7 on 2020-07-11 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0008_remove_application_first_pennapps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='first_hackathon',
            field=models.CharField(max_length=5),
        ),
    ]
